#!/usr/bin/env bash

if
  [[ -s "/home/adminuser/.rvm/gems/ruby-2.0.0-p481@global/environment" ]]
then
  source "/home/adminuser/.rvm/gems/ruby-2.0.0-p481@global/environment"
  exec gem "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/adminuser/.rvm/gems/ruby-2.0.0-p481@global/environment'" >&2
  exit 1
fi
