#!/usr/bin/env bash

if
  [[ -s "/home/adminuser/.rvm/gems/ruby-2.0.0-p481@railstutorial_rails_4_0/environment" ]]
then
  source "/home/adminuser/.rvm/gems/ruby-2.0.0-p481@railstutorial_rails_4_0/environment"
  exec irb "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/adminuser/.rvm/gems/ruby-2.0.0-p481@railstutorial_rails_4_0/environment'" >&2
  exit 1
fi
