#!/usr/bin/env bash

if
  [[ -s "/home/adminuser/.rvm/gems/ruby-2.0.0-p481/environment" ]]
then
  source "/home/adminuser/.rvm/gems/ruby-2.0.0-p481/environment"
  exec rdoc "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/adminuser/.rvm/gems/ruby-2.0.0-p481/environment'" >&2
  exit 1
fi
